name: data_leak
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  http: ^0.13.4
  flutter_typeahead: ^3.0.0
  firebase_core: 2.8.0
  firebase_auth: ^4.3.0
  firebase_database: ^10.0.16
  cloud_firestore: ^4.4.5
  provider: ^6.0.1
  flutter_spinkit: "^5.1.0"
  local_auth: ^1.1.9
  workmanager: ^0.5.1
  flutter_local_notifications: ^14.1.1
  flutter_secure_storage: ^8.0.0
  uuid: ^3.0.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
