// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdlEvjGoF1kItemRIM1dMCpmSKMu05bWk',
    appId: '1:178434390197:web:f0e0a4cc9162d14bace6fc',
    messagingSenderId: '178434390197',
    projectId: 'dataleakapp',
    authDomain: 'dataleakapp.firebaseapp.com',
    storageBucket: 'dataleakapp.appspot.com',
    measurementId: 'G-2K2RBLSMRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeq4LQML4u4BecccdZqznInWMR61Oh2nM',
    appId: '1:178434390197:android:d0b1f04f3cad7ab2ace6fc',
    messagingSenderId: '178434390197',
    projectId: 'dataleakapp',
    storageBucket: 'dataleakapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClL4S-yee5unbLsZK-iNn33f7zg4si3xE',
    appId: '1:178434390197:ios:f892c2b52f88e4acace6fc',
    messagingSenderId: '178434390197',
    projectId: 'dataleakapp',
    storageBucket: 'dataleakapp.appspot.com',
    iosClientId: '178434390197-qlvg6nerdnosopde201jkgr6961s3cs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataLeak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClL4S-yee5unbLsZK-iNn33f7zg4si3xE',
    appId: '1:178434390197:ios:f892c2b52f88e4acace6fc',
    messagingSenderId: '178434390197',
    projectId: 'dataleakapp',
    storageBucket: 'dataleakapp.appspot.com',
    iosClientId: '178434390197-qlvg6nerdnosopde201jkgr6961s3cs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataLeak',
  );
}
